### ISSUE TITLE
Feature suggestion: `VectorSelectable#[]` but always returns an array

### ISSUE THREAD

**Issue by KitaitiMakoto** [red-data-tools/red_amber#286]
Hello,

I would like to suggest to add method to retrieve values from `Vector` using indices like `VectorSelectable#[]` but which returns an array.

## Background ##

Suppose you work with e-commerce data including products and purchase transactions:

```ruby
products = DataFrame.new({
    code: %w[a        b        c        d        e        f        g       ],
    name: %w[ProductA ProductB ProductC ProductD ProductE ProductF ProductG]
})
purchases = DataFrame.new({
        customer: %w[A A B B C D D],
    product_code: %w[a b b c c d e]
})
```

Sub frames is very nice idea when you make report per customers:

```ruby
purchases.sub_by_value(:customer).each do |sub|
    product_indices = sub.product_code.collect {|code| products.code.index(code)}
    product_names = products.name[product_indices]

    sub.each_row.with_index do |row, index|
        purchased = {
                customer: row[:customer],
            product_code: row[:product_code],
            product_name: product_names[index]
        }
        pp purchased # call method to report, actually
    end
end
```

But, this doesn't work well:

```ruby
{:customer=>"A", :product_code=>"a", :product_name=>"ProductA"}
{:customer=>"A", :product_code=>"b", :product_name=>"ProductB"}
{:customer=>"B", :product_code=>"b", :product_name=>"ProductB"}
{:customer=>"B", :product_code=>"c", :product_name=>"ProductC"}
{:customer=>"C", :product_code=>"c", :product_name=>"P"}
{:customer=>"D", :product_code=>"d", :product_name=>"ProductD"}
{:customer=>"D", :product_code=>"e", :product_name=>"ProductE"}
```

There is a strange product name "P". This happens because `products.name[product_indices]` doesn't return `Array` but does `String` `"ProductC"` and `"Productc"[0]` returns `"P"` when `product_indices` is a single-value `Array`.

Of course, we can avoid this behavior by wrapping value which should be array with `Array()`: `product_names = Array(products.name[product_indices])`. But, it's hard to find strange behavior and fix it when you work with huge data, which is usual use case for data frame library.

I suggest to add method which always returns an `Array` even when return value is single value. I think `VectorSeletable#values_at` is good.

*I know we should use `#left_join` the case above, but this is an example to explain my motivation. My hope is a method that behaves consistently.*

I can implement such method and create a pull request. But let me hear what do you think about this before that.

**Comment by KitaitiMakoto** [comment]
My current implementation is here:

https://github.com/KitaitiMakoto/red_amber/blob/values-at/lib/red_amber/vector_selectable.rb#L101-L138

**Comment by heronshoes** [comment]
@KitaitiMakoto,
Thank you for your suggestion! And I am very sorry for waiting you so long. I'm back on line :-).

I think the points you have made are very important! I have two solutions:

1. Data Frame Joining is suitable for this example
2. Using `Vector#take` instead of `Vector#[]` always return Vector (not scalar)

I will explain them one by one.

**Comment by heronshoes** [comment]
## 1. Data Frame Joining is suitable for this example

This is a good example for Joining DataFrames. But column name in both tables are different. We can use a Hash to specify `join_key_pairs` in `DataFrame#join` family.

```ruby
purchases.inner_join(products, {left: :product_code, right: :code}) => df
df
# =>

#<RedAmber::DataFrame : 7 x 3 Vectors, 0x000000000003a6b0>
  customer product_code name
  <string> <string>     <string>
0 A        a            ProductA
1 A        b            ProductB
2 B        b            ProductB
3 B        c            ProductC
4 C        c            ProductC
5 D        d            ProductD
6 D        e            ProductE
```

It is better to use `#join` rather than to use pure Ruby code, because `#join` uses faster Arrow's C++ code in it.

If you need each rows in an Array, use `#each_row` Enumerator.

```ruby
df.each_row.to_a

# => 
[{:customer=>"A", :product_code=>"a", :name=>"ProductA"},
 {:customer=>"A", :product_code=>"b", :name=>"ProductB"},
 {:customer=>"B", :product_code=>"b", :name=>"ProductB"},
 {:customer=>"B", :product_code=>"c", :name=>"ProductC"},
 {:customer=>"C", :product_code=>"c", :name=>"ProductC"},
 {:customer=>"D", :product_code=>"d", :name=>"ProductD"},
 {:customer=>"D", :product_code=>"e", :name=>"ProductE"}]
```

**Comment by heronshoes** [comment]
## 2. Using `Vector#take` instead of `Vector#[]`. `#take` always returns a `Vector`

`Vector#[]` returns a scalar (String object for current case) when one index is specified. It returns an Array when multiple indices are specified by an Array or Vector.

`Vector#[]` is too much overloaded method. It is better to use `Vector#take` for this purpose. It always returns a Vector regardless of the size of the indices.

```ruby
products.name[0]
# =>
"ProductA"

products.name[0,1]
# =>
["ProductA", "ProductB"]

products.name.take(0)
# =>
#<RedAmber::Vector(:string, size=1, chunked):0x000000000004f7e0>
["ProductA"]

products.name.take(0, 1)
# => 
#<RedAmber::Vector(:string, size=2, chunked):0x00000000000516d0>
["ProductA", "ProductB"]
```

**Comment by KitaitiMakoto** [comment]
@heronshoes Thank you for reply!

I found `#join` family after I wrote script which uses `#[]`. Now I use `#join` in my script. That's nice!

I didn't know `Vector#take` method. It's what I want! Thanks for showing the method. 

I will close this issue.
